-- =====================================================
-- 테이블 및 컬럼 COMMENT 추가 스크립트
-- =====================================================

-- users 테이블 COMMENT
ALTER TABLE users COMMENT = '사용자 정보';
ALTER TABLE users MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '사용자 고유 ID';
ALTER TABLE users MODIFY COLUMN email VARCHAR(255) NOT NULL COMMENT '이메일 (로그인 ID)';
ALTER TABLE users MODIFY COLUMN name VARCHAR(255) NOT NULL COMMENT '사용자 이름';
ALTER TABLE users MODIFY COLUMN role VARCHAR(50) NOT NULL DEFAULT 'WORKER' COMMENT '역할 (ADMIN: 관리자, MANAGER: 매니저, WORKER: 작업자)';
ALTER TABLE users MODIFY COLUMN password VARCHAR(255) NOT NULL COMMENT '암호화된 비밀번호';
ALTER TABLE users MODIFY COLUMN is_active BOOLEAN DEFAULT TRUE COMMENT '계정 활성화 여부';
ALTER TABLE users MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시';
ALTER TABLE users MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시';

-- work_orders 테이블 COMMENT
ALTER TABLE work_orders COMMENT = '작업지시서 정보';
ALTER TABLE work_orders MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '작업지시서 고유 ID';
ALTER TABLE work_orders MODIFY COLUMN order_number VARCHAR(100) NOT NULL COMMENT '발주번호 (고유)';
ALTER TABLE work_orders MODIFY COLUMN supply_type VARCHAR(50) COMMENT '공급구분 (PRIMARY: 원청, SUBCONTRACT: 하청)';
ALTER TABLE work_orders MODIFY COLUMN company_name VARCHAR(255) COMMENT '업체명';
ALTER TABLE work_orders MODIFY COLUMN product_name VARCHAR(255) NOT NULL COMMENT '제품명';
ALTER TABLE work_orders MODIFY COLUMN product_code VARCHAR(100) COMMENT '제품코드';
ALTER TABLE work_orders MODIFY COLUMN quantity INT NOT NULL COMMENT '수량';
ALTER TABLE work_orders MODIFY COLUMN unit VARCHAR(20) DEFAULT 'EA' COMMENT '단위 (EA, BOX, SET, KG, M)';
ALTER TABLE work_orders MODIFY COLUMN due_date TIMESTAMP NOT NULL COMMENT '마감일';
ALTER TABLE work_orders MODIFY COLUMN priority VARCHAR(50) NOT NULL DEFAULT 'MEDIUM' COMMENT '우선순위 (LOW: 낮음, MEDIUM: 보통, HIGH: 높음, URGENT: 긴급)';
ALTER TABLE work_orders MODIFY COLUMN status VARCHAR(50) NOT NULL DEFAULT 'PENDING' COMMENT '상태 (PENDING: 대기, IN_PROGRESS: 진행중, PAUSED: 일시정지, COMPLETED: 완료, CANCELLED: 취소)';
ALTER TABLE work_orders MODIFY COLUMN work_type VARCHAR(50) COMMENT '작업유형 (PRODUCTION: 생산, ASSEMBLY: 조립, PACKAGING: 포장, INSPECTION: 검사, OTHER: 기타)';
ALTER TABLE work_orders MODIFY COLUMN instructions TEXT COMMENT '작업 지시사항';
ALTER TABLE work_orders MODIFY COLUMN selection VARCHAR(255) COMMENT '선택 사항';
ALTER TABLE work_orders MODIFY COLUMN progress INT DEFAULT 0 COMMENT '진행률 (0-100)';
ALTER TABLE work_orders MODIFY COLUMN assigned_to_id BIGINT COMMENT '담당자 ID (users.id 참조)';
ALTER TABLE work_orders MODIFY COLUMN started_at TIMESTAMP NULL COMMENT '작업 시작일시';
ALTER TABLE work_orders MODIFY COLUMN completed_at TIMESTAMP NULL COMMENT '작업 완료일시';
ALTER TABLE work_orders MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시';
ALTER TABLE work_orders MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시';

-- work_logs 테이블 COMMENT
ALTER TABLE work_logs COMMENT = '작업 이력 로그';
ALTER TABLE work_logs MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '로그 고유 ID';
ALTER TABLE work_logs MODIFY COLUMN work_order_id BIGINT NOT NULL COMMENT '작업지시서 ID (work_orders.id 참조)';
ALTER TABLE work_logs MODIFY COLUMN worker_id BIGINT NOT NULL COMMENT '작업자 ID (users.id 참조)';
ALTER TABLE work_logs MODIFY COLUMN action VARCHAR(50) NOT NULL COMMENT '수행 작업 (START: 시작, PAUSE: 일시정지, RESUME: 재개, COMPLETE: 완료, CANCEL: 취소)';
ALTER TABLE work_logs MODIFY COLUMN notes TEXT COMMENT '작업 메모';
ALTER TABLE work_logs MODIFY COLUMN progress INT COMMENT '진행률';
ALTER TABLE work_logs MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시';

-- issues 테이블 COMMENT
ALTER TABLE issues COMMENT = '이슈(품질/설비/안전 등) 관리';
ALTER TABLE issues MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '이슈 고유 ID';
ALTER TABLE issues MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '이슈 제목';
ALTER TABLE issues MODIFY COLUMN description TEXT COMMENT '이슈 상세 설명';
ALTER TABLE issues MODIFY COLUMN type VARCHAR(50) NOT NULL DEFAULT 'OTHER' COMMENT '이슈 유형 (EQUIPMENT: 설비, QUALITY: 품질, SAFETY: 안전, PROCESS: 공정, OTHER: 기타)';
ALTER TABLE issues MODIFY COLUMN status VARCHAR(50) NOT NULL DEFAULT 'OPEN' COMMENT '상태 (OPEN: 등록, IN_PROGRESS: 진행중, RESOLVED: 해결됨, CLOSED: 종료)';
ALTER TABLE issues MODIFY COLUMN priority VARCHAR(50) NOT NULL DEFAULT 'MEDIUM' COMMENT '우선순위 (LOW: 낮음, MEDIUM: 보통, HIGH: 높음, CRITICAL: 긴급)';
ALTER TABLE issues MODIFY COLUMN work_order_id BIGINT COMMENT '관련 작업지시서 ID (work_orders.id 참조)';
ALTER TABLE issues MODIFY COLUMN reported_by_id BIGINT COMMENT '보고자 ID (users.id 참조)';
ALTER TABLE issues MODIFY COLUMN assigned_to_id BIGINT COMMENT '담당자 ID (users.id 참조)';
ALTER TABLE issues MODIFY COLUMN resolution TEXT COMMENT '해결 내용';
ALTER TABLE issues MODIFY COLUMN resolved_at TIMESTAMP NULL COMMENT '해결일시';
ALTER TABLE issues MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시';
ALTER TABLE issues MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시';
